language: node_js
node_js:
  - "stable"
script:
  - npm run test
after_script:
  - npm run codecov
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
env:
  - HOST = "https://node-starter-kit.herokuapp.com"
  - NODE_ENV = "production"