branch-defaults:
  apple:
    environment: node-starter-kit2-dev
    group_suffix: null
global:
  application_name: node_starter_kit2
  branch: null
  default_ec2_keyname: nodejs
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
